# Generated by Django 3.2.17 on 2023-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this dashboard should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('FM', 'Finance Manager'), ('CM', 'Customer'), ('DR', 'Driver'), ('IV', 'Inventor Manager'), ('SP', 'Supplier'), ('PC', 'Packers'), ('AD', 'Admin')], default='CM', max_length=2)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this dashboard belongs to. A dashboard will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='dashboard', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this dashboard.', related_name='user_set', related_query_name='dashboard', to='auth.Permission', verbose_name='dashboard permissions')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
