# Generated by Django 3.2.17 on 2023-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('FM', 'Finance Manager'), ('CM', 'Customer'), ('DR', 'Driver'), ('IV', 'Inventory Manager'), ('SP', 'Supplier'), ('PC', 'Packers'), ('AD', 'Admin')], default='CM', max_length=2),
        ),
    ]
