# Generated by Django 3.2.17 on 2023-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('eggs', 'Eggs'), ('cakes', 'Cakes'), ('chicken', 'Chicken')], max_length=100)),
            ],
        ),
    ]
